1.数据获取

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


data = pd.read_csv('./bike.csv')
data

id  city  hour  is_workday  weather  temp_1  temp_2  wind    y
0         1     0    22           1        2     3.0     0.7     0   15
1         2     0    10           1        1    21.0    24.9     3   48
2         3     0     0           1        1    25.3    27.4     0   21
3         4     0     7           0        1    15.7    16.2     0   11
4         5     1    10           1        1    21.1    25.0     2   39
...     ...   ...   ...         ...      ...     ...     ...   ...  ...
9995   9996     0     4           0        2     8.3     7.3     0    2
9996   9997     1     5           0        1    22.3    22.2     0    1
9997   9998     1     0           0        1     9.6     9.7     0   11
9998   9999     0    18           0        2    27.4    29.7     1  105
9999  10000     0     9           1        2     3.2    -2.1     2   48

[10000 rows x 9 columns]

2.数据预处理 I

In [2]:
data = data.drop(columns=['id'])
data

city  hour  is_workday  weather  temp_1  temp_2  wind    y
0        0    22           1        2     3.0     0.7     0   15
1        0    10           1        1    21.0    24.9     3   48
2        0     0           1        1    25.3    27.4     0   21
3        0     7           0        1    15.7    16.2     0   11
4        1    10           1        1    21.1    25.0     2   39
...    ...   ...         ...      ...     ...     ...   ...  ...
9995     0     4           0        2     8.3     7.3     0    2
9996     1     5           0        1    22.3    22.2     0    1
9997     1     0           0        1     9.6     9.7     0   11
9998     0    18           0        2    27.4    29.7     1  105
9999     0     9           1        2     3.2    -2.1     2   48

[10000 rows x 8 columns]

3.数据预处理II

In [3]:
data = data.loc[data['city']==1]
data = data.drop(columns=['city'])
data

hour  is_workday  weather  temp_1  temp_2  wind    y
4       10           1        1    21.1    25.0     2   39
5        0           1        1    20.4    18.2     0   12
9        4           1        3    17.4    18.0     3    2
10       0           1        1    14.9    15.3     2    6
11       8           0        1    25.0    28.1     0   25
...    ...         ...      ...     ...     ...   ...  ...
9990    23           1        2    19.2    19.9     1   44
9991    19           1        1    25.1    26.2     2  124
9993     5           1        3    13.7    14.1     2    1
9996     5           0        1    22.3    22.2     0    1
9997     0           0        1     9.6     9.7     0   11

[4998 rows x 7 columns]

4.数据预处理III

In [4]:
data.loc[data['hour']>=19, 'hour']=0
data.loc[data['hour']<=5, 'hour']=0
data.loc[data['hour']!=0, 'hour']=1
data

hour  is_workday  weather  temp_1  temp_2  wind    y
4        1           1        1    21.1    25.0     2   39
5        0           1        1    20.4    18.2     0   12
9        0           1        3    17.4    18.0     3    2
10       0           1        1    14.9    15.3     2    6
11       1           0        1    25.0    28.1     0   25
...    ...         ...      ...     ...     ...   ...  ...
9990     0           1        2    19.2    19.9     1   44
9991     0           1        1    25.1    26.2     2  124
9993     0           1        3    13.7    14.1     2    1
9996     0           0        1    22.3    22.2     0    1
9997     0           0        1     9.6     9.7     0   11

[4998 rows x 7 columns]

5.数据预处理IV

In [5]:
y = data['y'].to_numpy()
y = y.reshape(len(y), 1)
data = data.drop(columns=['y'])
data

hour  is_workday  weather  temp_1  temp_2  wind
4        1           1        1    21.1    25.0     2
5        0           1        1    20.4    18.2     0
9        0           1        3    17.4    18.0     3
10       0           1        1    14.9    15.3     2
11       1           0        1    25.0    28.1     0
...    ...         ...      ...     ...     ...   ...
9990     0           1        2    19.2    19.9     1
9991     0           1        1    25.1    26.2     2
9993     0           1        3    13.7    14.1     2
9996     0           0        1    22.3    22.2     0
9997     0           0        1     9.6     9.7     0

[4998 rows x 6 columns]

6.数据预处理V

In [6]:
data = data.to_numpy()
print(type(data))

<class 'numpy.ndarray'>


7.数据集划分

In [7]:
x_train,x_test,y_train,y_test = train_test_split(data, y, test_size=0.2)

8.数据预处理VI

In [8]:
scale = MinMaxScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.fit_transform(x_test)
y_train = scale.fit_transform(y_train)
y_test = scale.fit_transform(y_test)
print(f'x_train:{x_train}')
print(f'y_train:{y_train}')
print(f'x_test:{x_test}')
print(f'y_test:{y_test}')

x_train:[[1.         1.         0.5        0.63392857 0.58181818 0.        ]
 [1.         1.         1.         0.64508929 0.6231405  0.28571429]
 [1.         1.         1.         0.43303571 0.45619835 0.28571429]
 ...
 [0.         0.         0.         0.56919643 0.56363636 0.14285714]
 [1.         1.         0.         0.82366071 0.74710744 0.28571429]
 [1.         0.         0.         0.72098214 0.71570248 0.28571429]]
y_train:[[0.50769231]
 [0.73333333]
 [0.07179487]
 ...
 [0.33333333]
 [0.27179487]
 [0.27692308]]
x_test:[[0.         0.         0.         0.34894614 0.34935897 0.14285714]
 [1.         1.         0.         0.95784543 0.9375     0.28571429]
 [0.         1.         1.         0.1498829  0.23717949 0.        ]
 ...
 [0.         1.         1.         0.43793911 0.44711538 0.14285714]
 [1.         0.         0.         0.66978923 0.61538462 0.        ]
 [1.         0.         0.         0.96487119 0.84615385 0.14285714]]
y_test:[[0.00546448]
 [0.62295082]
 [0.08196721

9.模型构建

In [9]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

10.模型测试

In [10]:
y_predict = model.predict(x_test)

11.模型评估

In [11]:
print(mean_squared_error(y_test,y_predict)**0.5)

0.1747916868937477
